import { spawnSync } from "node:child_process";

const tests = [
  ["scripts/generate-core-catalog.mjs", "--check"],
  "scripts/check-manifest-execution-parity.mjs",
  "scripts/check-core-boundaries.mjs",
  "scripts/check-active-docs.mjs",
  ["scripts/generate-kit-ownership-ledger.mjs", "--check"],
  ["scripts/generate-root-module-dispositions.mjs", "--check"],
  ["scripts/generate-protokit-extraction.mjs", "--check"],
  ["scripts/generate-public-test-surface.mjs", "--check"],
  ["scripts/generate-dsk-manifest.mjs", "--check"],
  ["scripts/generate-guide.mjs", "--check"],
  "examples/guide/basic-engine.mjs",
  "examples/guide/object-placement.mjs",
  "examples/guide/composition-inspection.mjs",
  "tests/public-api-freeze.mjs",
  "tests/public-entrypoint-relative-targets-smoke.mjs",
  "tests/runtime-kit-idempotency-smoke.mjs",
  "tests/domain-service-kit-smoke.mjs",
  "tests/domain-path-api-registration-smoke.mjs",
  "tests/core-domain-kits-smoke.mjs",
  "src/core-domains/tests/domain-manifest-contract.mjs",
  "tests/core-world-domain.mjs",
  "tests/core-domains/world-foundation-domain-smoke.mjs",
  "tests/core-domains/world-feature-domain-smoke.mjs",
  "tests/core-domains/landform-feature-domain-smoke.mjs",
  "tests/core-domains/world-feature-catalog-smoke.mjs",
  "tests/core-domains/world-feature-foundation-integration.mjs",
  "tests/core-domains/world-terrain-compatibility.mjs",
  "src/core-domains/world/tests/restored-world-behaviors.mjs",
  "src/core-domains/spatial/tests/spatial-scale-restoration.mjs",
  "src/core-domains/simulation/tests/restored-motion-behaviors.mjs",
  "src/core-domains/simulation/tests/restored-economy-operations.mjs",
  "src/core-domains/interaction/tests/restored-interaction-behaviors.mjs",
  "src/core-domains/simulation/tests/restored-progression-pressure.mjs",
  "src/core-domains/presentation/tests/third-person-camera-restoration.mjs",
  "tests/core-domains/core-weather-domain-smoke.mjs",
  "tests/sequence-node-library-smoke.mjs",
  "tests/sequence-node-runtime-smoke.mjs",
  "tests/sequence-node-frame-driver-smoke.mjs",
  "tests/sequence-node-kit-deploy-smoke.mjs",
  "tests/sequence-node-surface-bridge-smoke.mjs",
  "tests/core-capability-domain-barrels-smoke.mjs",
  "tests/realtime-core-tick-contract-smoke.mjs",
  "tests/core-kits/core-data-kit-smoke.mjs",
  "tests/core-kits/core-object-kit-smoke.mjs",
  "tests/core-kits/core-input-kit-smoke.mjs",
  "tests/core-kits/core-scene-kit-smoke.mjs",
  "tests/core-kits/core-motion-kit-smoke.mjs",
  "tests/core-kits/core-utility-articulation-smoke.mjs",
  "tests/core-kits/core-graphics-kit-smoke.mjs",
  "tests/core-kits/core-graphics-procedural-material-smoke.mjs",
  "tests/core-kits/core-graphics-reflection-kit-smoke.mjs",
  "tests/core-kits/core-graphics-render-layer-graph-contract.mjs",
  "tests/core-kits/core-graphics-render-layer-graph-smoke.mjs",
  "tests/core-domains/core-graphics-domain-smoke.mjs",
  "tests/core-kits/core-simulation-kit-smoke.mjs",
  "tests/core-kits/core-promoted-services-smoke.mjs",
  "tests/core-kits/core-child-capabilities-smoke.mjs",
  "tests/core-kits/core-simulation-resolution-smoke.mjs",
  "tests/core-kits/core-physics-provider-smoke.mjs",
  "tests/core-domains/core-motion-domain-smoke.mjs",
  "tests/core-domains/core-physics-domain-smoke.mjs",
  "tests/core-domains/core-compute-domain-smoke.mjs",
  "tests/core-domains/core-capture-domain-smoke.mjs",
  "tests/core-domains/core-object-shape-domain-smoke.mjs",
  "tests/core-domains/core-object-shape-skinned-qualification-smoke.mjs",
  "tests/core-domains/core-capture-shape-visual-smoke.mjs",
  "tests/core-domains/core-object-fidelity-domain-smoke.mjs",
  "tests/core-domains/core-object-vegetation-domain-smoke.mjs",
  "tests/core-domains/core-object-vegetation-natural-growth-smoke.mjs",
  "src/core-domains/object/tests/object-domain-smoke.mjs",
  "src/core-domains/object/subdomains/placement/tests/placement-smoke.mjs",
  "src/core-domains/object/subdomains/placement/tests/placement-roundtrip.mjs",
  "src/core-domains/mcp/tests/mcp-registry-smoke.mjs",
  "src/core-domains/mcp/tests/mcp-contract-negative.mjs",
  "src/core-domains/mcp/tests/node-stdio-smoke.mjs",
  "src/core-domains/composition/tests/composition-mcp-smoke.mjs",
  "src/core-domains/build/tests/domain-tree.mjs",
  "src/core-domains/build/tests/dependency-resolution.mjs",
  "src/core-domains/build/tests/project-immutability.mjs",
  "src/core-domains/build/tests/multi-target.mjs",
  "src/core-domains/build/tests/full-build-loop.mjs",
  "src/core-domains/build/tests/native-lowering.mjs",
  "src/core-domains/build/tests/cli-contract.mjs",
  "src/core-domains/build/tests/mcp-build.mjs",
  "src/core-domains/build/tests/web-target-browser.mjs",
  "tests/core-domains/core-creature-character-player-smoke.mjs",
  "tests/core-domains/core-speech-domain-smoke.mjs",
  "tests/core-kits/core-interaction-kit-smoke.mjs",
  "tests/core-kits/core-mlnn-kit-smoke.mjs",
  "tests/core-kits/core-agent-kit-smoke.mjs",
  "tests/core-kits/core-debug-kit-smoke.mjs",
  "tests/core-kits/core-startup-domain-smoke.mjs",
  "tests/core-kits/core-assets-async-smoke.mjs",
  "tests/core-kits/core-assets-bundle-smoke.mjs",
  "tests/core-kits/core-assets-cache-smoke.mjs",
  "tests/core-kits/core-assets-deduplication-smoke.mjs",
  "tests/core-kits/core-assets-startup-bridge-smoke.mjs",
  "tests/core-kits/core-presentation-domain-smoke.mjs",
  "tests/core-kits/core-custom-replacement-smoke.mjs"
];

for (const test of tests) {
  const [script, ...args] = Array.isArray(test) ? test : [test];
  const result = spawnSync(process.execPath, [script, ...args], {
    stdio: "inherit",
    cwd: process.cwd()
  });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

console.log(`Passed ${tests.length} smoke tests.`);
